### PR TITLE
Added background color option that would override theme color and default color.

### PR DESCRIPTION
**Pull request by namanshergill**

### CODE REVIEW

**Comment by deengel** [comment]
When will this feature be merged to master? I'm really looking forward to override the background color....

**Comment by namanshergill** [comment]
> When will this feature be merged to master? I'm really looking forward to override the background color....

You can depend on this branch directly if you would like, add this to your yaml
```yaml
  flutter_highlight:
    git:
      url: https://github.com/NamanShergill/highlight.dart.git
      ref: 6d982b74e50ca18e7be712971fd42ab5e96ae1fb
      path: flutter_highlight
```

**Comment by namanshergill** [comment]
I'm just going to close this PR, I don't think anyone is going to check it.

**Comment by deengel** [comment]
Hi Naman, why did you close the PR? I would love to see the backgroundColor feature on master.

**Pull request closed without merging**
